language: php
matrix:
  allow_failures:
    - php: 5.4

  include:
    - php: 5.4 # lowest versions of all dependencies
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
install:
  - composer self-update && composer --version

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE suitecrm_automated_tests;'
script:
  - ./vendor/bin/codecept run
  - cat ../suitecrm.log
services:
  - mysql
branches:
  only:
    - master
    - hotfix
    - develop
    - /feature.*/
