language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 5.4
matrix:
  allow_failures:
    - php: 5.4
before_script:
  - mysql -e "CREATE DATABASE automated_tests CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
  - mysql -u root -e "CREATE USER 'automated_tests'@'localhost' IDENTIFIED BY 'automated_tests';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON automated_tests.* TO 'automated_tests'@'localhost';"
  - composer self-update
  - composer install --no-interaction
  - \[ -f "config_si.php" \] || cp tests/travis_config_si.php config_si.php
  - php tests/testinstall.php
  # Lint PHP
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"; then exit 1; fi

script:
  - cd tests
  - ../vendor/bin/phpunit
  - cat ../suitecrm.log
services:
  - mysql
branches:
  only:
    - master
    - develop
    - /hotfix.*/
    - /feature.*/
    - /fix.*/
